### ISSUE TITLE
SurgeonTool not appearing in RF4

### ISSUE THREAD

**Issue by LettError** [connordavenport/BezierSurgeon#3]
In RF Version 4.1b (build 2110011334), when I install BezierSurgeon from this repository, select the item from the menu, this is printed in the output. No surgeons appear. 

```Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 95, in sendEvent_
  File "lib/eventTools/eventManager.pyc", line 308, in toolbarCallback_
  File "lib/eventTools/eventManager.pyc", line 257, in setActiveEventByIndex_
  File "lib/eventTools/baseEventTool.pyc", line 235, in _base_becomeInactive
  File "BezierSurgeon.py", line 265, in becomeInactive
AttributeError: 'SurgeonTool' object has no attribute 'SurgeonToolUI'

**Comment by connordavenport** [comment]
There is currently a complete rewrite so I'm going to close this:)
